name: Create documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**/*'

jobs:
  docs:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - uses: fwcd/swift-docc-action@v1
      with:
        target: SolanaSwift
        output: ./docs
        hosting-base-path: solana-swift
        disable-indexing: 'true'
        transform-for-static-hosting: 'true'

    - name: Init new repo for docs
      run: |
        cd docs
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs
        force: true
        directory: ./docs
